### ISSUE TITLE
exe版本，下载的时候容易闪退

### ISSUE THREAD

**Issue by huamumian** [smloli/tujigu#2]
exe版本，下载的时候闪退
比如这个只下载到No.389就闪退了.
![image](https://user-images.githubusercontent.com/41187381/144350495-d901c7f8-e25d-4f17-8164-b87d6c9fcedf.png)

**Comment by smloli** [comment]
> exe版本，下载的时候闪退 比如这个只下载到No.389就闪退了. ![image](https://user-images.githubusercontent.com/41187381/144350495-d901c7f8-e25d-4f17-8164-b87d6c9fcedf.png)

拖动软件到cmd里运行，查看闪退原因

**Comment by oxygen0424** [comment]
时间间隔能更改嘛 5秒太长了

**Comment by smloli** [comment]
> 时间间隔能更改嘛 5秒太长了

间隔只会变长不会变短，尽量不影响人家网站正常运行

**Comment by oxygen0424** [comment]
那能否更新一个创建文件夹功能 按标签分好 所有文件在一个太堆积

**Comment by smloli** [comment]
> 那能否更新一个创建文件夹功能 按标签分好 所有文件在一个太堆积

已更新

**Comment by oxygen0424** [comment]
https://pic.mba/image/Q9qg
这是闪退的反馈

**Comment by smloli** [comment]
未出现闪退
![1.png](https://dd-static.jd.com/ddimg/jfs/t1/167098/6/22034/129015/61ab0c29E3bfac58d/56489423e7bea39f.png)
![2.png](https://dd-static.jd.com/ddimg/jfs/t1/211082/9/11547/138948/61ab0c29E09b0efbe/b35014f06f11ea8e.png)

**Comment by oxygen0424** [comment]
重下的话 还是间隔5秒检测一下 如何快速定位到上次下载位置

**Comment by smloli** [comment]
> 重下的话 还是间隔5秒检测一下 如何快速定位到上次下载位置

已下载状态取消时间限制
